# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-23 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyNav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, verbose_name='图片')),
                ('name', models.CharField(max_length=100)),
                ('trackid', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '导航数据',
                'db_table': 'axf_nav',
            },
        ),
        migrations.AlterModelOptions(
            name='mywheel',
            options={'verbose_name': '轮播数据'},
        ),
    ]
