"""empty message

Revision ID: 656ecf3b0a63
Revises: 7ef351695f04
Create Date: 2018-08-07 15:39:48.095993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656ecf3b0a63'
down_revision = '7ef351695f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('u_permission', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'u_permission')
    # ### end Alembic commands ###
